---
title: "Tagesbericht Covid19"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
author: "Angelo Schleussner"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE,}
library(readr)
library(dplyr)
library(psych)
library(ggplot2)
library(tidyverse)
library(magrittr)
library(lubridate)
library(tidyr)
library(zoo)
library(plotly)
library(knitr)
library(kableExtra)
library(RColorBrewer)
library(ggthemes)

rm(list=ls())  #Loescht alle Vorherigen Variablen und Daten aus R
setwd("~/Desktop/R Studio Test")

#Umlaute darstellen
Sys.setlocale("LC_ALL", "de_DE.UTF-8") 

#Website der Daten
#https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data

#Aktuellen Datensatz laden, wenn es Datum des Datensatzes nicht von heutigem Datum ist. (Ungleich des Systemdatums)
#Speichern in "~/Desktop/R Studio Test". Filename "RKI_COVID19.csv"

url="https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data"

if (!file.exists(paste0("data/RKI/RKI_COVID19_",Sys.Date(),".csv"))) {
  download.file(url,destfile = paste0("~/Desktop/R Studio Test/data/RKI/RKI_COVID19_",Sys.Date(),".csv"))
}

##Datensatz importieren, Daten ohne Uhrzeit, nach Meldedatum sortieren----

if (!exists("RKI_COVID19")) {
  RKI_COVID19 <- read_csv(paste0("data/RKI/RKI_COVID19_",Sys.Date(),".csv")) %>% 
    mutate(Meldedatum = ymd(as.Date(Meldedatum)),
           Refdatum = ymd(as.Date(Refdatum)),
           Datenstand = as_date(dmy_hm(Datenstand)))%>% 
    arrange(desc(Meldedatum))

}

#Beginn der Lockdowns setzten
Lockdown1 = as.Date("2020-03-22")
Lockdown2 = as.Date("2020-11-02")
```




## Fallzahlen Heute

###Deutschland
```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
Bund_ZumVortag_df = RKI_COVID19 %>%
  filter(NeuerFall %in% c(-1,1)) %>% 
  summarise(Bundesland = "Gesamt",
            "Differenz zum Vortag" = sum(AnzahlFall)) 

#Anzahl aller Covid Fälle seit beginn  (Anzahl Fälle der aktuellen Publikation als Summe(AnzahlFall), wenn NeuerFall in (0,1))
Bund_Fälle_Gesamt_df = RKI_COVID19 %>%
  filter(NeuerFall %in% c(0,1)) %>%
  summarise(Bundesland = "Gesamt",
            Anzahl = sum(AnzahlFall))

Bund_Tabelle_df = full_join(Bund_ZumVortag_df, Bund_Fälle_Gesamt_df, by = "Bundesland")


Bund_Tabelle_df %>% 
  `colnames<-`(c("","Differenz zum Vortag","Anzahl")) %>% 
  kbl(booktabs = F, linesep = "")%>%
  kable_classic(full_width = F, 
                position = "left") %>%  
  kable_styling("hover",
                full_width = F,
                position = "left",
                fixed_thead = T)
```


###Städte
```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
Städte = c("SK Düsseldorf","SK Darmstadt","SK Frankfurt am Main")
Städte_ZumVortag_df = RKI_COVID19 %>% 
  filter(NeuerFall %in% c(-1,1)) %>% 
  filter(Landkreis %in% Städte) %>% 
  group_by(Landkreis) %>% 
  summarise(AnzahlFall = sum(AnzahlFall)) %>%
  `colnames<-`(c("Landkreis","Differenz zum Vortag")) 


Städte_FälleGesamt_df = RKI_COVID19 %>% 
  filter(NeuerFall %in% c(0,1)) %>% 
  filter(Landkreis %in% Städte) %>% 
  group_by(Landkreis) %>% 
  summarise(AnzahlFall = sum(AnzahlFall)) %>%
  `colnames<-`(c("Landkreis","Anzahl"))  


Städte_Tabelle_df = full_join(Städte_ZumVortag_df, Städte_FälleGesamt_df, by = "Landkreis")

Städte_Tabelle_df %>% 
kbl(booktabs = F, linesep = "")%>%
  kable_classic(full_width = F, 
                position = "left") %>%  
  kable_styling("hover",
                full_width = F,
                position = "left",
                fixed_thead = T)
```

###Bundesländer
```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
#Bundesländer Tabelle. Infektionen zum Vortag 
#Bundesländer heute zum Vortag neue Fälle nach Bundesland
Bundeslaender_ZumVortag_df = RKI_COVID19 %>% 
  filter(NeuerFall %in% c(-1,1)) %>% 
  group_by(Bundesland) %>% 
  summarise(AnzahlFall = sum(AnzahlFall)) %>%
  `colnames<-`(c("Bundesland","Differenz zum Vortag")) %>% 
  arrange(Bundesland)

#Bundesländer Fälle Gesamt
Bundeslaender_FälleGesamt_df = RKI_COVID19 %>% 
  filter(NeuerFall %in% c(0,1)) %>% 
  group_by(Bundesland) %>% 
  summarise(AnzahlFall = sum(AnzahlFall)) %>% 
  `colnames<-`(c("Bundesland","Anzahl")) %>% 
  arrange(Bundesland)

#Bundesländer Tabelle. Infektionen zum Vortag
Bundesländer_Tabelle_df = full_join(Bundeslaender_ZumVortag_df, Bundeslaender_FälleGesamt_df,  by = "Bundesland")


Bundesländer_Bund_Tabelle_df = bind_rows(Bundesländer_Tabelle_df,Bund_Tabelle_df)

Bundesländer_Bund_Tabelle_df%>%
  kbl(booktabs = F, linesep = "")%>%
  kable_classic(full_width = F, 
                position = "left") %>% 
  row_spec(17,
           bold = T,
           background = "gray") %>% 
  kable_styling("hover",
                full_width = F,
                position = "left",
                fixed_thead = T)

Neufindektion_Datum_df <- read_csv("data/Erstellt/Neufindektion_Datum_df.csv")

Neufindektion_Datum_df %>% 
    kbl(booktabs = F, linesep = "")%>%
  kable_classic(full_width = F, 
                position = "left") %>% 
  kable_styling("hover",
                full_width = F,
                position = "left",
                fixed_thead = T)
```

##Zeitlicher Verlauf

###Graphen {.tabset}

####Bund
```{r ,fig.width=10, fig.height=6,echo=FALSE,warning=FALSE,message=FALSE}
#Bund
Plott_Bund=RKI_COVID19 %>% 
  filter(NeuerFall %in% c(0,1)) %>% 
  group_by(Meldedatum) %>% 
  summarise(AnzahlFall = sum(AnzahlFall)) %>% 
  mutate(max_AnzahlFall=ifelse(AnzahlFall==max(AnzahlFall), "1", "0")) %>% 
  ggplot(aes(Meldedatum,AnzahlFall,fill=max_AnzahlFall)) +
  ggtitle("Bund")+
  scale_fill_manual( values = c( "1"="red", "0"="black" ), guide = FALSE)+
  geom_col( width = 0.7) +
  geom_vline(xintercept = as.numeric(Lockdown1), color = "#000066", size=0.5,alpha=0.9) +
  geom_vline(xintercept = as.numeric(Lockdown2), color = "#000066", size=0.5,alpha=0.9) +
  scale_x_date(date_breaks = "1 month",
               date_minor_breaks = "1 weeks",
               date_labels = "%b %y")+
  coord_cartesian(xlim = c(as.Date("2020-03-01"),NA),
                  ylim = c(0,NA)) + #zoom the plot (magnifying glass), not change underlying data (like limit)
  theme_minimal()+
  theme(legend.position = "none")+
  stat_smooth(size=0.7,se=T)

ggplotly(Plott_Bund)


```

####Darmstadt
```{r ,fig.width=10, fig.height=6,echo=FALSE,warning=FALSE,message=FALSE}

SK_Darmstadt_df = RKI_COVID19 %>% 
  filter(NeuerFall %in% c(0,1)) %>% 
  filter(Landkreis == "SK Darmstadt") %>% 
  group_by(Meldedatum) %>% 
  summarise(AnzahlFall = sum(AnzahlFall)) %>% 
  arrange(desc(Meldedatum)) 

Plott_Darmstadt = ggplot(SK_Darmstadt_df,aes(Meldedatum,AnzahlFall)) +
  ggtitle("Darmstadt") +
  geom_col(color = "black", width = 0.2) +
  geom_vline(xintercept = as.numeric(Lockdown1), color = "#000066", size=0.5,alpha=0.9) +
  geom_vline(xintercept = as.numeric(Lockdown2), color = "#000066", size=0.5,alpha=0.9)+
  scale_x_date(date_breaks = "1 month",
               date_minor_breaks = "1 weeks",
               date_labels = "%b %y")+
  coord_cartesian(xlim = c(as.Date("2020-03-01"),NA),
                  ylim = c(0,NA)) + #zoom the plot (magnifying glass), not change underlying data (like limit)
  theme_minimal()+
  stat_smooth(size=0.7,se=T)

ggplotly(Plott_Darmstadt)
```

####Bundesländer
```{r ,fig.width=10, fig.height=10,echo=FALSE,warning=FALSE,message=FALSE}

Bundesländer_df = RKI_COVID19 %>% 
  filter(NeuerFall %in% c(0,1)) %>% 
  group_by(Meldedatum, Bundesland,NeuerFall) %>% 
  summarise(AnzahlFall = sum(AnzahlFall)) %>% 
  arrange(desc(Meldedatum)) 

Plott_Bundesländer = ggplot(Bundesländer_df,aes(Meldedatum,AnzahlFall)) +
  geom_col(aes(fill = Bundesland,color=Bundesland))+
  geom_vline(xintercept = as.numeric(Lockdown2), color = "#000066", size=0.3,alpha=0.9)+
  scale_x_date(date_breaks = "1 month",
               date_labels = "%m")+
  coord_cartesian(xlim = c(Sys.Date()-90,NA),
                  ylim = c(0,NA)) + #zoom the plot (magnifying glass), not change underlying data (like limit)
  facet_wrap(~ Bundesland, ncol=4, scales="free_y")+
  theme_fivethirtyeight()+
  theme(legend.position = "none")+
  stat_smooth(color = "black",size = 0.5,se = FALSE)

ggplotly(Plott_Bundesländer)

```
